export const TYPES = {
    AppArgs: Symbol('AppArgs'),
    AppStoreArgs: Symbol('AppStoreArgs'),
    ClassLoaderArgs: Symbol('ClassLoaderArgs'),
    ClassroomCreatorArgs: Symbol('ClassroomCreatorArgs'),
    DataSubscriberArgs: Symbol('DataSubscriberArgs'),
    FirebaseReference: Symbol('FirebaseReference'),
    HeaderCreatorArgs: Symbol('HeaderCreatorArgs'),
    IApp: Symbol('IApp'),
    IClassroomCreator: Symbol('IClassroomCreator'),
    IClassLoader: Symbol('IClassLoader'),
    IDataSubscriber: Symbol('IDataSubscriber'),
    IHeaderCreator: Symbol('IHeaderCreator'),
    IVueConfigurer: Symbol('IVueConfigurer'),
    IStudentViewCreator: Symbol('IStudentViewCreator'),
    IState: Symbol('IState'),
    ITeacherViewCreator: Symbol('ITeacherClassViewerCreator'),
    ITeacherLoader: Symbol('ITeacherLoader'),
    ITopicCreator: Symbol('ITopicCreator'),
    Store: Symbol('Store'),
    StudentViewCreatorArgs: Symbol('StudentViewCreatorArgs'),
    TeacherViewCreatorArgs: Symbol('TeacherViewCreatorArgs'),
    TopicCreatorArgs: Symbol('TopicCreatorArgs'),
    TeacherLoaderArgs: Symbol('TeacherLoaderArgs'),
    VueConfigurerArgs: Symbol('VueConfigurerArgs'),
}